module.exports = (sequelize, Sequelize) => {
  const job_history = sequelize.define(
    "job_history",
    {
      id: {
        type: Sequelize.DataTypes.INTEGER,
        primaryKey: true,
        autoIncrement: true,
      },
      repair_date: Sequelize.DataTypes.STRING,
      invoice_date: Sequelize.DataTypes.STRING,
      police_no: Sequelize.DataTypes.STRING,
      model_type: Sequelize.DataTypes.STRING,
      model: Sequelize.DataTypes.STRING,
      customer: Sequelize.DataTypes.STRING,
      nik: Sequelize.DataTypes.STRING,
      alamat: Sequelize.DataTypes.STRING,
      kelurahan: Sequelize.DataTypes.STRING,
      kecamatan: Sequelize.DataTypes.STRING,
      kabupaten: Sequelize.DataTypes.STRING,
      norangka: Sequelize.DataTypes.STRING,
      invoice_no: Sequelize.DataTypes.STRING,
      no_order: Sequelize.DataTypes.STRING,
      customer_type: Sequelize.DataTypes.STRING,
      job: Sequelize.DataTypes.STRING,
      job_sbe: Sequelize.DataTypes.STRING,
      repair_type: Sequelize.DataTypes.STRING,
      ro: Sequelize.DataTypes.STRING,
      last_km: Sequelize.DataTypes.STRING,
      sa: Sequelize.DataTypes.STRING,
      tech: Sequelize.DataTypes.STRING,
      rate: Sequelize.DataTypes.STRING,
      jasa: Sequelize.DataTypes.STRING,
      part: Sequelize.DataTypes.STRING,
      oil: Sequelize.DataTypes.STRING,
      material: Sequelize.DataTypes.STRING,
      sublet: Sequelize.DataTypes.STRING,
      discount: Sequelize.DataTypes.STRING,
      ppn: Sequelize.DataTypes.STRING,
      materai: Sequelize.DataTypes.STRING,
      total: Sequelize.DataTypes.STRING,
      piutang: Sequelize.DataTypes.STRING,
      tunai: Sequelize.DataTypes.STRING,
      disc_jasa: Sequelize.DataTypes.STRING,
      disc_part: Sequelize.DataTypes.STRING,
      no_bp: Sequelize.DataTypes.STRING,
      dealer: Sequelize.DataTypes.STRING,
    },
    {
      freezeTableName: true,
      underscored: true,
      timestamps: false,
      createdAt: false,
      updatedAt: false,
    }
  );

  return job_history;
};
